<?php

/**
 * @file
 * diff_field type general hooks
 */

use Drupal\node\NodeInterface;
use Drupal\node\NodeTypeInterface;



/**
 * Implements hook_node_load().
 */
/**function diff_field_load(NodeInterface $node) {

  // do something
  $x12="diff_field";
  drupal_set_message($x12);
}
*/
/**
 * Implements hook_node_update().
 */
function diff_field_node_update(NodeInterface $node) {

  // do something
  $num_updated = db_update('node_revision__field_hemlata')
  ->fields(array(
    'field_hemlata_after_rid' => $node->getRevisionId(),
  ))
  ->condition('entity_id', $node->id(), '=')
  ->execute();
}


/**
 * Implements hook_node_presave().
 */
 /**
function diff_field_node_presave(NodeInterface $node) {
	$x="Yahoo";
	//$xyz=$node->id();
  drupal_set_message($xyz);
  drupal_set_message($x);
  //die("p");
}
*/
?>

